name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        python_version:
        - "3.11"
        - "3.12"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install dependencies
      run: |
        pip install -r server/requirements.txt
    - name: Run end-to-end tests
      run: |
        bash ./run_tests.sh
