name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-backend:
    strategy:
      # Should help with debugging (do all versions fail or just old ones)
      fail-fast: false
      matrix:
        python_version:
        - "3.11"
        - "3.12"
        - "3.13"
    name: "Test backend code (Python ${{ matrix.python_version }})"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt
    - name: Run end-to-end tests
      run: |
        bash ./scripts/run_tests.sh
